name: "Codeception Tests"
on:
  push:
    branches:
      - '*'
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            include:
                - { php-version: 8.1, dependencies: lowest, pimcore_version: "", experimental: false }
                - { php-version: 8.3, dependencies: highest, pimcore_version: "", experimental: false }
                - { php-version: 8.3, dependencies: highest, pimcore_version: "11.x-dev as 11.0.0", experimental: true }
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: curl, mbstring, openssl, pdo, pdo_sqlite
          ini-values: memory_limit=-1, date.timezone='UTC'
          coverage: xdebug
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: "Update Pimcore version"
        env:
            PIMCORE_VERSION: "${{ matrix.pimcore_version }}"
        run: |
            if [ ! -z "$PIMCORE_VERSION" ]; then
                  composer require --no-update pimcore/pimcore:"${PIMCORE_VERSION}"
            fi  

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: Run tests
        run: php vendor/bin/codecept run

