name: "PHP-CS-Fixer"

on:
    pull_request:
        types: [ opened,closed,synchronize ]
    push:
        branches:
            - "[0-9]+.[0-9]+"
            - "[0-9]+.x"
            - "*_actions"
            - "feature-*"
            -
permissions:
    contents: write

jobs:
    php-style:
        if: github.repository_owner == 'pimcore'
        uses: pimcore/workflows-collection-public/.github/workflows/reusable-php-cs-fixer.yaml@cstest
        secrets:
            PHP_CS_FIXER_GITHUB_TOKEN: ${{ secrets.PHP_CS_FIXER_GITHUB_TOKEN }}
        with:
            head_ref: ${{ github.event.pull_request.head.ref }}
            repository: ${{ github.event.pull_request.head.repo.full_name }}
            config_file: .php-cs-fixer.dist.php