name: Generate SBOM

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Adjust the PHP version to match your project

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --no-interaction

      - name: Generate CycloneDX SBOM
        uses: CycloneDX/gh-php-composer-generate-sbom@v1
        with:
          output-file: 'sbom.xml'
          format: 'xml'

      - name: Upload SBOM as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.xml